const DATASET_BASE_URL =
  'https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos';

const BRAND_SLUG_OVERRIDES: Record<string, string> = {
  'alfa romeo': 'alfa-romeo',
  'aston martin': 'aston-martin',
  'bmw motorrad': 'bmw',
  'ds automobiles': 'ds',
  'great wall': 'great-wall',
  'harley davidson': 'harley-davidson',
  'land rover': 'land-rover',
  'mercedes benz': 'mercedes-benz',
  'mercedes-benz': 'mercedes-benz',
  'mini cooper': 'mini',
  'moto guzzi': 'moto-guzzi',
  'mv agusta': 'mv-agusta',
  'royal enfield': 'royal-enfield',
  'rolls royce': 'rolls-royce',
};

const BRAND_LABEL_OVERRIDES: Record<string, string> = {
  "9ff": "9ff",
  "abt": "ABT",
  "ac": "AC",
  "amc": "AMC",
  "bac": "BAC",
  "baic-motor": "BAIC Motor",
  "bmw": "BMW",
  "bmw-m": "BMW M",
  "byd": "BYD",
  "camc": "CAMC",
  "chevrolet-corvette": "Chevrolet Corvette",
  "daf": "DAF",
  "ds": "DS",
  "faw": "FAW",
  "gmc": "GMC",
  "hsv": "HSV",
  "ikco": "IKCO",
  "iran-khodro": "Iran Khodro",
  "iveco": "IVECO",
  "jac": "JAC",
  "jmc": "JMC",
  "ktm": "KTM",
  "ldv": "LDV",
  "mg": "MG",
  "mini": "MINI",
  "nio": "NIO",
  "ram": "RAM",
  "saic-motor": "SAIC Motor",
  "scg": "SCG",
  "seat": "SEAT",
  "ssangyong": "SsangYong",
  "ssc": "SSC",
  "swm": "SWM",
  "tvr": "TVR",
  "vinfast": "VinFast"
};

const AVAILABLE_BRAND_SLUGS = [
  "9ff",
  "abadal",
  "abarth",
  "abbott-detroit",
  "abt",
  "ac",
  "acura",
  "aiways",
  "aixam",
  "alfa-romeo",
  "alpina",
  "alpine",
  "alta",
  "alvis",
  "amc",
  "apollo",
  "arash",
  "arcfox",
  "ariel",
  "aro",
  "arrinera",
  "arrival",
  "artega",
  "ascari",
  "askam",
  "aspark",
  "aston-martin",
  "atalanta",
  "auburn",
  "audi",
  "audi-sport",
  "austin",
  "autobacs",
  "autobianchi",
  "axon",
  "bac",
  "baic-motor",
  "baojun",
  "beiben",
  "bentley",
  "berkeley",
  "berliet",
  "bertone",
  "bestune",
  "bharatbenz",
  "bitter",
  "bizzarrini",
  "bmw",
  "bmw-m",
  "borgward",
  "bowler",
  "brabus",
  "brammo",
  "brilliance",
  "bristol",
  "brooke",
  "bufori",
  "bugatti",
  "buick",
  "byd",
  "byton",
  "cadillac",
  "camc",
  "canoo",
  "caparo",
  "carlsson",
  "caterham",
  "changan",
  "changfeng",
  "chery",
  "chevrolet",
  "chevrolet-corvette",
  "chrysler",
  "cisitalia",
  "citroen",
  "cizeta",
  "cole",
  "corre-la-licorne",
  "cupra",
  "dacia",
  "daewoo",
  "daf",
  "daihatsu",
  "daimler",
  "dartz",
  "datsun",
  "david-brown",
  "dayun",
  "de-tomaso",
  "delage",
  "desoto",
  "detroit-electric",
  "devel-sixteen",
  "diatto",
  "dina",
  "dkw",
  "dmc",
  "dodge",
  "dodge-viper",
  "dongfeng",
  "donkervoort",
  "drako",
  "ds",
  "duesenberg",
  "eagle",
  "edag",
  "edsel",
  "eicher",
  "elemental",
  "elfin",
  "elva",
  "englon",
  "erf",
  "eterniti",
  "exeed",
  "facel-vega",
  "faraday-future",
  "faw",
  "faw-jiefang",
  "ferrari",
  "fiat",
  "fioravanti",
  "fisker",
  "foden",
  "force-motors",
  "ford",
  "ford-mustang",
  "foton",
  "fpv",
  "franklin",
  "freightliner",
  "fso",
  "gac-group",
  "gardner-douglas",
  "gaz",
  "geely",
  "general-motors",
  "genesis",
  "geo",
  "geometry",
  "gilbern",
  "gillet",
  "ginetta",
  "gmc",
  "golden-dragon",
  "gonow",
  "great-wall",
  "grinnall",
  "gumpert",
  "hafei",
  "haima",
  "haval",
  "hawtai",
  "hennessey",
  "higer",
  "hillman",
  "hindustan-motors",
  "hino",
  "hiphi",
  "hispano-suiza",
  "holden",
  "hommell",
  "honda",
  "hongqi",
  "hongyan",
  "horch",
  "hsv",
  "hudson",
  "hummer",
  "hupmobile",
  "hyundai",
  "ic-bus",
  "ih",
  "ikco",
  "infiniti",
  "innocenti",
  "intermeccanica",
  "international",
  "irizar",
  "isdera",
  "iso",
  "isuzu",
  "iveco",
  "jac",
  "jaguar",
  "jawa",
  "jba-motors",
  "jeep",
  "jensen",
  "jetour",
  "jetta",
  "jmc",
  "kaiser",
  "kamaz",
  "karlmann-king",
  "karma",
  "keating",
  "kenworth",
  "kia",
  "king-long",
  "koenigsegg",
  "ktm",
  "lada",
  "lagonda",
  "lamborghini",
  "lancia",
  "land-rover",
  "landwind",
  "laraki",
  "leapmotor",
  "levc",
  "lexus",
  "leyland",
  "li-auto",
  "lifan",
  "ligier",
  "lincoln",
  "lister",
  "lloyd",
  "lobini",
  "lordstown",
  "lotus",
  "lucid",
  "luxgen",
  "lynk-and-co",
  "mack",
  "mahindra",
  "man",
  "mansory",
  "marcos",
  "marlin",
  "maserati",
  "mastretta",
  "maxus",
  "maybach",
  "maz",
  "mazda",
  "mazzanti",
  "mclaren",
  "melkus",
  "mercedes-amg",
  "mercedes-benz",
  "mercury",
  "merkur",
  "mev",
  "mg",
  "microcar",
  "mini",
  "mitsubishi",
  "mitsuoka",
  "mk",
  "morgan",
  "morris",
  "mosler",
  "navistar",
  "nevs",
  "nikola",
  "nio",
  "nissan",
  "nissan-gt-r",
  "nissan-nismo",
  "noble",
  "oldsmobile",
  "oltcit",
  "omoda",
  "opel",
  "osca",
  "paccar",
  "packard",
  "pagani",
  "panhard",
  "panoz",
  "pegaso",
  "perodua",
  "peterbilt",
  "peugeot",
  "pgo",
  "pierce-arrow",
  "pininfarina",
  "plymouth",
  "polestar",
  "pontiac",
  "porsche",
  "praga",
  "premier",
  "prodrive",
  "proton",
  "qoros",
  "radical",
  "ram",
  "rambler",
  "ranz",
  "renault",
  "renault-samsung",
  "rezvani",
  "riley",
  "rimac",
  "rinspeed",
  "rivian",
  "roewe",
  "rolls-royce",
  "ronart",
  "rossion",
  "rover",
  "ruf",
  "saab",
  "saic-motor",
  "saipa",
  "saleen",
  "saturn",
  "scania",
  "scion",
  "seat",
  "setra",
  "sev",
  "shacman",
  "simca",
  "singer",
  "singulato",
  "sinotruk",
  "sisu",
  "skoda",
  "smart",
  "soueast",
  "spania-gta",
  "spirra",
  "spyker",
  "ssangyong",
  "ssc",
  "sterling",
  "studebaker",
  "stutz",
  "subaru",
  "suffolk",
  "suzuki",
  "talbot",
  "tata",
  "tatra",
  "tauro",
  "techart",
  "tesla",
  "toyota",
  "toyota-alphard",
  "toyota-century",
  "toyota-crown",
  "tramontana",
  "trion",
  "triumph",
  "troller",
  "tucker",
  "tvr",
  "uaz",
  "ud",
  "ultima",
  "vandenbrink",
  "vauxhall",
  "vector",
  "vencer",
  "venturi",
  "venucia",
  "vinfast",
  "vlf",
  "volkswagen",
  "volvo",
  "w-motors",
  "wanderer",
  "wartburg",
  "weltmeister",
  "western-star",
  "westfield",
  "wey",
  "wiesmann",
  "willys-overland",
  "workhorse",
  "wuling",
  "xpeng",
  "yulon",
  "yutong",
  "zarooq-motors",
  "zastava",
  "zaz",
  "zeekr",
  "zenos",
  "zenvo",
  "zhongtong",
  "zinoro",
  "zotye"
] as const;

export interface BrandOption {
  label: string;
  slug: string;
}

function normalizeBrand(value: string) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function slugifyBrand(value: string) {
  return normalizeBrand(value).replace(/\s+/g, '-');
}

function titleizeSlug(slug: string) {
  return slug
    .split('-')
    .map(chunk => chunk.charAt(0).toUpperCase() + chunk.slice(1))
    .join(' ');
}

export function getBrandSlug(brand: string) {
  const normalizedBrand = normalizeBrand(brand);
  return BRAND_SLUG_OVERRIDES[normalizedBrand] ?? slugifyBrand(brand);
}

export function getBrandLabel(slug: string) {
  return BRAND_LABEL_OVERRIDES[slug] ?? titleizeSlug(slug);
}

export const BRAND_OPTIONS: BrandOption[] = AVAILABLE_BRAND_SLUGS.map(slug => ({
  slug,
  label: getBrandLabel(slug),
}));

export function getBrandOptionByLabel(label: string) {
  const normalizedLabel = normalizeBrand(label);
  return BRAND_OPTIONS.find(option => normalizeBrand(option.label) === normalizedLabel) ?? null;
}

export function getBrandLogoUrl(brand: string, variant: 'thumb' | 'optimized' = 'optimized') {
  if (!brand.trim()) {
    return null;
  }

  return `${DATASET_BASE_URL}/${variant}/${getBrandSlug(brand)}.png`;
}
